# Beverage companies
Beverage = ['CELH', 'DEO', 'FTXG', 'KDP', 'KO', 'MNST', 'PBJ', 'PEP', 'PRMW', 'SAM', 'STZ', 'TAP']

# Large companies
Big_Guys = ['XOM', 'SHEL', 'VLO', 'CAH', 'HSIC', 'KO', 'AMC']

# SP500
Universe = ['A', 'AAL', 'AAP', 'AAPL', 'ABBV', 'ABC', 'ABT', 'ACN', 'ADBE', 'ADI', 'ADM', 'ADP', 'ADS', 'ADSK', 'AEE', 'AEP', 
'AES', 'AET', 'AFL', 'AGN', 'AIG', 'AIV', 'AIZ', 'AJG', 'AKAM', 'ALB', 'ALGN', 'ALK', 'ALL', 'ALLE', 'ALXN', 'AMAT', 'AMD', 'AME', 
'AMG', 'AMGN', 'AMP', 'AMT', 'AMZN', 'ANDV', 'ANSS', 'ANTM', 'AON', 'AOS', 'APA', 'APC', 'APD', 'APH', 'APTV', 'ARE', 'ARNC', 
'ATVI', 'AVB', 'AVGO', 'AVY', 'AWK', 'AXP', 'AYI', 'AZO', 'BA', 'BAC', 'BAX', 'BBT', 'BBY', 'BDX', 'BEN', 'BF.B', 'BHF', 'BHGE', 
'BIIB', 'BK', 'BKNG', 'BLK', 'BLL', 'BMY', 'BRK.B', 'BSX', 'BWA', 'BXP', 'C', 'CA', 'CAG', 'CAH', 'CAT', 'CB', 'CBOE', 'CBRE', 
'CBS', 'CCI', 'CCL', 'CDNS', 'CELG', 'CERN', 'CF', 'CFG', 'CHD', 'CHRW', 'CHTR', 'CI', 'CINF', 'CL', 'CLX', 'CMA', 'CMCSA', 'CME', 
'CMG', 'CMI', 'CMS', 'CNC', 'CNP', 'COF', 'COG', 'COL', 'COO', 'COP', 'COST', 'COTY', 'CPB', 'CRM', 'CSCO', 'CSX', 'CTAS', 'CTL', 
'CTSH', 'CTXS', 'CVS', 'CVX', 'CXO', 'D', 'DAL', 'DE', 'DFS', 'DG', 'DGX', 'DHI', 'DHR', 'DIS', 'DISCA', 'DISCK', 'DISH', 'DLR', 
'DLTR', 'DOV', 'DPS', 'DRE', 'DRI', 'DTE', 'DUK', 'DVA', 'DVN', 'DWDP', 'DXC', 'EA', 'EBAY', 'ECL', 'ED', 'EFX', 'EIX', 'EL', 
'EMN', 'EMR', 'EOG', 'EQIX', 'EQR', 'EQT', 'ES', 'ESRX', 'ESS', 'ETFC', 'ETN', 'ETR', 'EVHC', 'EW', 'EXC', 'EXPD', 'EXPE', 'EXR', 
'F', 'FAST', 'FB', 'FBHS', 'FCX', 'FDX', 'FE', 'FFIV', 'FIS', 'FISV', 'FITB', 'FL', 'FLIR', 'FLR', 'FLS', 'FMC', 'FOX', 'FOXA', 
'FRT', 'FTI', 'FTV', 'GD', 'GE', 'GGP', 'GILD', 'GIS', 'GLW', 'GM', 'GOOG', 'GOOGL', 'GPC', 'GPN', 'GPS', 'GRMN', 'GS', 'GT', 
'GWW', 'HAL', 'HAS', 'HBAN', 'HBI', 'HCA', 'HCP', 'HD', 'HES', 'HIG', 'HII', 'HLT', 'HOG', 'HOLX', 'HON', 'HP', 'HPE', 'HPQ', 
'HRB', 'HRL', 'HRS', 'HSIC', 'HST', 'HSY', 'HUM', 'IBM', 'ICE', 'IDXX', 'IFF', 'ILMN', 'INCY', 'INFO', 'INTC', 'INTU', 'IP', 
'IPG', 'IPGP', 'IQV', 'IR', 'IRM', 'ISRG', 'IT', 'ITW', 'IVZ', 'JBHT', 'JCI', 'JEC', 'JNJ', 'JNPR', 'JPM', 'JWN', 'K', 'KEY', 
'KHC', 'KIM', 'KLAC', 'KMB', 'KMI', 'KMX', 'KO', 'KORS', 'KR', 'KSS', 'KSU', 'L', 'LB', 'LEG', 'LEN', 'LH', 'LKQ', 'LLL', 'LLY', 
'LMT', 'LNC', 'LNT', 'LOW', 'LRCX', 'LUK', 'LUV', 'LYB', 'M', 'MA', 'MAA', 'MAC', 'MAR', 'MAS', 'MAT', 'MCD', 'MCHP', 'MCK', 'MCO', 
'MDLZ', 'MDT', 'MET', 'MGM', 'MHK', 'MKC', 'MLM', 'MMC', 'MMM', 'MNST', 'MO', 'MON', 'MOS', 'MPC', 'MRK', 'MRO', 'MS', 'MSCI', 
'MSFT', 'MSI', 'MTB', 'MTD', 'MU', 'MYL', 'NAVI', 'NBL', 'NCLH', 'NDAQ', 'NEE', 'NEM', 'NFLX', 'NFX', 'NI', 'NKE', 'NKTR', 'NLSN', 
'NOC', 'NOV', 'NRG', 'NSC', 'NTAP', 'NTRS', 'NUE', 'NVDA', 'NWL', 'NWS', 'NWSA', 'O', 'OKE', 'OMC', 'ORCL', 'ORLY', 'OXY', 'PAYX', 
'PBCT', 'PCAR', 'PCG', 'PEG', 'PEP', 'PFE', 'PFG', 'PG', 'PGR', 'PH', 'PHM', 'PKG', 'PKI', 'PLD', 'PM', 'PNC', 'PNR', 'PNW', 'PPG', 
'PPL', 'PRGO', 'PRU', 'PSA', 'PSX', 'PVH', 'PWR', 'PX', 'PXD', 'PYPL', 'QCOM', 'QRVO', 'RCL', 'RE', 'REG', 'REGN', 'RF', 'RHI', 
'RHT', 'RJF', 'RL', 'RMD', 'ROK', 'ROP', 'ROST', 'RRC', 'RSG', 'RTN', 'SBAC', 'SBUX', 'SCG', 'SCHW', 'SEE', 'SHW', 'SIVB', 'SJM', 
'SLB', 'SLG', 'SNA', 'SNPS', 'SO', 'SPG', 'SPGI', 'SRCL', 'SRE', 'STI', 'STT', 'STX', 'STZ', 'SWK', 'SWKS', 'SYF', 'SYK', 'SYMC', 
'SYY', 'T', 'TAP', 'TDG', 'TEL', 'TGT', 'TIF', 'TJX', 'TMK', 'TMO', 'TPR', 'TRIP', 'TROW', 'TRV', 'TSCO', 'TSN', 'TSS', 'TTWO', 
'TWX', 'TXN', 'TXT', 'UA', 'UAA', 'UAL', 'UDR', 'UHS', 'ULTA', 'UNH', 'UNM', 'UNP', 'UPS', 'URI', 'USB', 'UTX', 'V', 'VAR', 'VFC', 
'VIAB', 'VLO', 'VMC', 'VNO', 'VRSK', 'VRSN', 'VRTX', 'VTR', 'VZ', 'WAT', 'WBA', 'WDC', 'WEC', 'WELL', 'WFC', 'WHR', 'WLTW', 'WM', 
'WMB', 'WMT', 'WRK', 'WU', 'WY', 'WYN', 'WYNN', 'XEC', 'XEL', 'XL', 'XLNX', 'XOM', 'XRAY', 'XRX', 'XYL', 'YUM', 'ZBH', 'ZION', 
'ZTS']

# NYSE - Sector - Communication Services
NYSE_COMM_SRVS = ["ABLV","ADD","ADTH","ADV","AENT","AGAE","AMC","AMCX","AMX","ANGH","ANGI","ANTE","AREN","ASST","ASTS","ATEX","ATHM","ATNI","ATUS","ATVI","AVID",
                  "BAOS","BATRA","BATRK","BBGI","BCE","BHAT","BIDU","BILI","BOC","BODY","BOWL","BRAG","BREA","BZFD","CABO","CARG","CCO","CCOI","CDLX","CHT","CHTR",
                  "CMCM","CMCSA","CMLS","CMPR","CNET","CNK","CNSL","CNVS","COMS","CPOP","CRTO","CSSE","CTV","CURI","CXDO","DALN","DASH","DDI","DIS","DISH","DLPN",
                  "DLX","DOYU","DRCT","EA","EDR","EDUC","EEX","EGLX","EVC","EVER","FAZE","FENG","FLNT","FNGR","FOX","FOXA","FUBO","FVRR","FWONA","FYBR","GAIA",
                  "GAME","GCI","GDC","GDEV","GENI","GETY","GIGM","GMGI","GOGO","GOOG","GOOGL","GROM","GRPN","GRVY","GSAT","GSMG","GTN","GTN.A","HHS","HOFV","HRYU",
                  "HUYA","IAC","IAS","ICLK","IDCC","IDT","IHRT","IHS","IMAX","INUV","IPG","IQ","IRDM","IZEA","JFIN","KIND","KORE","KRKR","KT","KUKE","LBRDA",
                  "LBRDK","LBTYA","LBTYB","LBTYK","LCFY","LDWY","LEE","LGF.A","LGF.B","LILA","LILAK","LIZI","LKCO","LPTV","LTRPA","LTRPB","LUMN","LVO","LYV",
                  "MANU","MATH","MAX","MCHX","MCS","MDIA","META","MGAM","MGNI","MGOL","MIMO","MMV","MOBQ","MOMO","MOXC","MSGE","MSGM","MSGS","MTCH","MYPS","NCMI",
                  "NCTY","NFLX","NFTG","NN","NTES","NWS","NWSA","NXST","NYT","OB","OMC","ONFO","OOMA","OPRA","ORAN","PARA","PARAA","PERI","PHI","PINS","PLAY",
                  "PLTK","PODC","PSO","QNST","RBBN","RBLX","RCI","RDCM","RDI","RDIB","RELX","ROKU","RSVR","SALM","SBGI","SCHL","SCOR","SCPL","SEAT","SGA","SHEN",
                  "SIFY","SIRI","SJ","SKLZ","SKM","SLE","SMWB","SNAL","SNAP","SOHU","SPHR","SPOT","SSP","SSTK","STBX","STCN","STGW","T","TBLA","TC","TDS","TEO",
                  "TGNA","THRY","TIGO","TIMB","TKC","TKO","TLK","TME","TMUS","TOON","TRKA","TRMR","TRUE","TRVG","TSQ","TTGT","TTWO","TU","TV","TWLO","TZOO","UCL",
                  "UONE","UONEK","UPXI","USM","VEON","VIV","VOD","VSME","VZ","WB","WBD","WIMI","WLY","WLYB","WMG","WOW","WPP","XNET","YELP","YY","Z","ZD","ZDGE",
                  "ZG","ZH"]

# NYSE - Sector - Consumer Discretionary
NYSE_CONSUMER_DISCRETIONARY = ["AAP","ABG","ABNB","ACEL","ACVA","ADNT","AEO","AEVA","AGS","AIN","AKA","ALLG","ALSN","ALV","AMBP","AMCR","AMWD","AMZN","AN",
                               "ANF","AOUT","APRN","APTV","ARCO","AREB","ARHS","ARKO","ARKR","ARVL","ASO","ATAT","ATER","AUVI","AXL","AYRO","AZO","BABA",
                               "BALL","BALY","BARK","BBW","BBWI","BBY","BC","BDL","BERY","BETS","BFAM","BFI","BGFV","BGI","BH","BH.A","BIRD","BJRI","BKE",
                               "BKNG","BLBD","BLMN","BNED","BOOT","BQ","BRLT","BROS","BSET","BTBD","BURL","BVH","BWA","BWMX","BYD","BZH","BZUN","CAAS","CAKE",
                               "CAL","CANG","CARS","CASY","CATO","CAVA","CBD","CBRL","CCK","CCL","CCS","CDRO","CENN","CHDN","CHH","CHPT","CHS","CHSN","CHUY",
                               "CHWY","CJET","CLAR","CMG","CNNE","CNTY","CNXA","COLM","CONN","COOK","CPHC","CPNG","CPRI","CPRT","CPS","CRI","CRMT","CROX","CRWS",
                               "CSV","CTHR","CTNT","CTRN","CUK","CULP","CURV","CVCO","CVGI","CVNA","CWH","CZOO","CZR","DADA","DAN","DBGI","DBI","DDS","DECK",
                               "DENN","DESP","DFH","DHI","DIBS","DIN","DKNG","DKS","DLA","DLTH","DOGZ","DOOO","DORM","DPZ","DRI","DRVN","DSS","DTC","DXLG",
                               "DXYN","EAT","EBAY","EBET","ECX","EFOI","EJH","ELA","ELYS","EM","ESCA","ETD","ETSY","EVGO","EVRI","EVTV","EXPE","EXPR","EXTO",
                               "EYE","EZGO","F","FAT","FATBB","FFIE","FGH","FGI","FIGS","FIVE","FL","FLL","FLWS","FLXS","FND","FNKO","FORD","FOSL","FOXF",
                               "FRGI","FRSX","FRZA","FSR","FTCH","FTDR","FTEL","FUN","FUV","FWRG","GAMB","GAN","GCO","GDEN","GDHG","GEF","GEF.B","GENK","GES",
                               "GGR","GHG","GIII","GIL","GLBE","GM","GMBL","GME","GNTX","GOEV","GOLF","GOOS","GP","GPC","GPI","GPK","GPS","GRBK","GRWG","GT",
                               "GTIM","GTX","H","HAS","HBB","HBI","HD","HEPS","HGV","HIBB","HLLY","HLT","HMC","HNST","HOFT","HOG","HOUR","HOV","HRB","HSAI",
                               "HTHT","HVT","HYLN","HYZN","HZO","ID","IGT","IHG","INSE","INTG","INVZ","IP","IPW","IRBT","ISPO","IVP","JACK","JAKK","JD","JEWL",
                               "JFBR","JILL","JMIA","JOAN","JOUT","JRSH","JWEL","JWN","JXJT","JZXN","KAR","KBH","KEQU","KFS","KIRK","KMX","KNDI","KRT","KRUS",
                               "KSS","KTB","KXIN","LAD","LAKE","LANV","LAZR","LAZY","LCID","LCII","LCUT","LE","LEA","LEG","LEGH","LEN","LEN.B","LESL","LEVI",
                               "LGIH","LI","LIDR","LIND","LITB","LIVE","LKQ","LL","LNW","LOCO","LOVE","LOW","LQDT","LTH","LTRY","LULU","LUXH","LVLU","LVS",
                               "LVWR","LZB","M","MAR","MAT","MBC","MBLY","MBUU","MCD","MCFT","MCOM","MCRI","MCW","MDC","MED","MELI","MGA","MGIH","MGM","MHK",
                               "MHO","MI","MLCO","MLKN","MLR","MMYT","MNRO","MNSO","MOD","MODG","MOGU","MOND","MOV","MPAA","MPX","MRM","MSC","MTH","MTN","MULN",
                               "MUSA","MYE","MYTE","NAAS","NATH","NCLH","NCNC","NDLS","NEGG","NGMS","NHTC","NIO","NIU","NKE","NLS","NTZ","NVFY","NVR","NVVE",
                               "NWTN","OCG","OCTO","ODP","OI","OLPX","ONEW","ONON","ORLY","OSTK","OSW","OXM","PACK","PAG","PATK","PBPB","PDD","PENN","PEV",
                               "PHIN","PHM","PII","PIK","PKG","PLBY","PLCE","PLNT","PLOW","PLYA","POL","PRPL","PRTS","PSNY","PTLO","PTON","PTVE","PVH","PZZA",
                               "QRTEA","QRTEB","QS","QSR","RACE","RAVE","RCKY","RCL","REAL","REBN","REE","RENT","RERE","REYN","RGS","RH","RICK","RIVN","RL",
                               "RMBL","ROL","ROST","ROVR","RRGB","RRR","RSI","RUSHA","RUSHB","RVLV","SABR","SAH","SBET","SBH","SBUX","SCI","SCVL","SDA","SE",
                               "SEAS","SECO","SEE","SES","SFIX","SFT","SG","SGC","SGHC","SHAK","SHCO","SHOO","SIG","SIX","SKX","SKY","SLGN","SLNA","SMP","SN",
                               "SNBR","SOLO","SON","SOND","SPGC","SPWH","SRI","SRM","SSU","STKS","STLA","STRT","SUP","SVV","SYPR","TAST","TCOM","TCS","TDUP",
                               "THCH","THO","THRM","TILE","TJX","TLF","TLYS","TM","TMHC","TNL","TOL","TOUR","TPH","TPR","TPX","TRIP","TRNR","TRS","TSCO",
                               "TSLA","TTSH","TUP","TXRH","UA","UAA","UCAR","UFAB","UFI","UHG","ULTA","URBN","UXIN","VAC","VC","VEEE","VEV","VFC","VFS",
                               "VIOT","VIPS","VIRC","VLCN","VMAR","VNCE","VRA","VRM","VSCO","VSTO","W","WEN","WEYS","WGO","WH","WHR","WINA","WING","WISH",
                               "WKHS","WKSP","WNW","WOOF","WPRT","WRK","WSM","WW","WWW","WYNN","XELB","XPEL","XPEV","XPOF","XWEL","YETI","YHGJ","YJ","YOSH",
                               "YSG","YTRA","YUM","YUMC","ZAPP","ZGN","ZUMZ"]

# NYSE - Sector - Consumer Staples
NYSE_CONSUMER_STAPLES = ["AACG","ABEV","ACI","ACU","ADM","AFRI","AFYA","AGRI","AGRO","AIU","AKO.A","AKO.B","ALCO","AMBO","ANDE","APEI","AQB","ARCE",
                         "ASAI","ATGE","AVO","BEDU","BF.A","BF.B","BG","BGS","BIG","BJ","BOF","BON","BRBR","BRCC","BRFH","BRFS","BRID","BRSH","BSFC",
                         "BTCT","BTI","BTOG","BTTR","BUD","BYND","CAG","CALM","CCEP","CCU","CELH","CENT","CENTA","CHD","CHEF","CHGG","CL","CLEU","CLX",
                         "COCO","COE","COKE","COST","COTY","COUR","CPB","CVGW","CYAN","DAO","DAR","DDL","DEO","DG","DIT","DLTR","DNUT","DOLE","DTCK",
                         "EAST","EDBL","EDTK","EDU","EEIQ","EL","ELF","EPC","EWCZ","FAMI","FARM","FDP","FEDU","FIZZ","FLO","FMX","FREE","FRPT","FTLF",
                         "GEHI","GHC","GIS","GNLN","GNS","GO","GOTU","GROV","GSUN","HAIN","HELE","HFFG","HIMS","HLF","HRL","HSY","IH","IMKTA","INGR",
                         "IPAR","ISPR","JBSS","JJSF","JVA","JZ","K","KAVL","KDP","KHC","KLG","KMB","KO","KOF","KR","KVUE","LANC","LAUR","LFVN","LINC",
                         "LMNR","LND","LOCL","LOPE","LQR","LRN","LSF","LW","LWAY","LXEH","MAMA","MDLZ","MF","MGPI","MKC","MNST","MO","MSS","MTEX",
                         "NAII","NAPA","NATR","NCRA","NGVC","NOMD","NTCO","NUS","NUZE","NWL","OLLI","OTLY","PAVS","PEP","PETZ","PFGC","PG","PLAG","PM",
                         "POST","PPC","PRDO","PRMW","PSMT","QSG","RGF","RIBT","RLX","RMCF","SAM","SANW","SBEV","SDOT","SENEA","SENEB","SFM","SJM","SKIL",
                         "SKIN","SMFL","SMPL","SNAX","SOVO","SPB","SPTN","STG","STKH","STKL","STRA","STZ","SYY","TAL","TANH","TAP","TEDU","TGT","THRN",
                         "THS","TKLF","TPB","TR","TSN","TWNK","TWOU","UDMY","UG","UL","UNFI","USFD","USNA","UTI","UTZ","UVV","VEDU","VFF","VGR","VINE",
                         "VITL","VLGEA","VSTA","VTRU","VWE","WAFU","WEST","WILC","WMK","WMT","WTER","WVVI","XXII","YGF","YQ","ZVIA"]

# NYSE - Sector - Energy
NYSE_ENERGY = ["ACDC","AE","AESI","AM","AMPY","AMTX","APA","AR","ARCH","ARLP","AROC","BANL","BATL","BKR","BNMV","BOOM","BORR","BP","BPT","BRN","BROG",
               "BRY","BSM","BTE","BTU","CAPL","CCJ","CCLP","CEI","CEIX","CEQP","CHK","CHRD","CHX","CIVI","CKX","CLB","CLMT","CLNE","CNQ","CNX","COP","CPE",
               "CPG","CQP","CRC","CRGY","CRK","CRT","CSAN","CTRA","CVE","CVI","CVX","DEN","DHT","DINO","DK","DKL","DLNG","DMLP","DNN","DNOW","DO","DRQ",
               "DTI","DTM","DVN","DWSN","E","EC","EFXT","EGY","ENB","ENLC","ENSV","EOG","EP","EPD","EPM","EPSN","EQNR","EQT","ERF","ESTE","ET","ETRN",
               "EU","EURN","FANG","FET","FLNG","FRO","FTI","FTK","GEL","GEOS","GLNG","GLP","GPOR","GPP","GPRK","GTE","HAL","HEP","HES","HESM","HHRS",
               "HLX","HNRG","HP","HPK","HUSA","ICD","IMO","IMPP","INDO","INSW","KGS","KLXE","KMI","KNTK","KOS","KRP","LBRT","LEU","LNG","LPG","MARPS",
               "MGY","MMLP","MPC","MPLX","MRC","MRO","MTDR","MTR","MUR","MXC","NBR","NC","NCSM","NE","NEXT","NFG","NGL","NGS","NINE","NOA","NOG","NOV",
               "NR","NRP","NRT","NS","NVGS","NXE","OBE","OII","OIS","OKE","OSG","OVV","OXY","PAGP","PARR","PBA","PBF","PBR","PBR.A","PBT","PDS","PED",
               "PFIE","PHX","PNRG","PR","PRT","PSX","PTEN","PUMP","PVL","PXD","RCON","REI","REPX","RES","RIG","RNGR","RRC","SBOW","SBR","SD","SDPI",
               "SDRL","SGU","SHEL","SJT","SLB","SLCA","SLNG","SM","SMLP","SND","SOI","STNG","SU","SUN","SWN","TALO","TDW","TELL","TGS","TK","TNK","TNP",
               "TPET","TPL","TRGP","TRMD","TRP","TS","TTE","TTI","TXO","UEC","UGP","URG","UROY","USAC","USEG","UUUU","VAL","VET","VIST","VIVK","VLO",
               "VNOM","VOC","VTLE","VTNR","VTOL","VTS","VVV","WDS","WES","WFRD","WHD","WKC","WMB","WTI","WTTR","XOM","XPRO","YPF"]

# NYSE - Sector - Financials
NYSE_FINANCIALS = ["AAC","AACI","AACT","AAMC","AAME","AB","ABCB","ABL","AC","ACAB","ACAC","ACAH","ACAQ","ACAX","ACBA","ACGL","ACIC","ACNB","ACRO","ACT",
                   "ADEX","ADOC","ADRT","AEAE","AEG","AEL","AFAR","AFBI","AFG","AFL","AGBA","AGM","AGM.A","AGO","AHG","AIB","AIG","AIHS","AIMAU","AINC",
                   "AIZ","AJG","ALCC","ALCY","ALL","ALLY","ALOR","ALRS","ALSA","ALTI","ALTU","AMAL","AMAO","AMBC","AMG","AMK","AMNB","AMP","AMRK","AMSF",
                   "AMTB","AMTD","AOGO","AON","AONC","APAC","APAM","APCA","APGB","APLD","APO","APTM","APXI","AQU","ARBK","ARCC","ARES","ARGO","ARIZ",
                   "AROW","ARRW","ARTE","ARYD","ASA","ASB","ASCA","ASCB","ASPA","ASRV","ATAK","ATEK","ATIF","ATLC","ATLO","ATMC","ATMV","AUB","AUBN",
                   "AVAL","AVHI","AVTA","AX","AXP","AXS","BAC","BACA","BAFN","BAM","BANC","BANF","BANR","BANX","BAP","BBAR","BBD","BBDC","BBDO","BBUC",
                   "BBVA","BCAL","BCBP","BCH","BCML","BCOW","BCS","BCSA","BCSF","BEN","BENF","BETR","BFAC","BFC","BFH","BFIN","BFST","BGC","BHAC","BHB",
                   "BHF","BHLB","BHRB","BIOS","BITE","BITF","BK","BKCC","BKU","BLAC","BLEU","BLFY","BLK","BLUA","BLX","BMA","BMAC","BMO","BMRC","BN",
                   "BNIX","BNRE","BNS","BOAC","BOCN","BOH","BOKF","BOTJ","BOWN","BPOP","BPRN","BRAC","BRBS","BRD","BRDG","BREZ","BRK.A","BRK.B","BRKH",
                   "BRKL","BRLI","BRO","BRP","BSAC","BSBK","BSBR","BSIG","BSRR","BST","BSVN","BTBT","BTCS","BTM","BTWN","BUJA","BUR","BUSE","BWAQ","BWB",
                   "BWFG","BX","BXSL","BY","BYFC","BYN","BYNO","BYTS","C","CAC","CACC","CADE","CALB","CARE","CARV","CASH","CATC","CATY","CB","CBAN","CBFV",
                   "CBNK","CBOE","CBRG","CBSH","CBU","CCAP","CCB","CCBG","CCG","CCNE","CCTS","CCV","CCVI","CDAQ","CET","CETU","CFB","CFBK","CFFE","CFFI",
                   "CFFN","CFFS","CFG","CFIV","CFR","CFSB","CG","CGBD","CHAA","CHCO","CHEA","CHMG","CIA","CIB","CIFR","CINF","CION","CITE","CIVB","CIZN",
                   "CLAY","CLBK","CLIN","CLM","CLOE","CLRC","CLST","CM","CMA","CMCA","CME","CNA","CNDA","CNDB","CNF","CNFR","CNGL","CNO","CNOB","CNS",
                   "COCH","COF","COFS","COHN","COLB","CONX","COOL","COOP","CPF","CPSS","CPTK","CRBG","CRD.A","CRD.B","CRVL","CSLM","CSLR","CSTA","CSTR",
                   "CSWC","CTBI","CUBI","CULL","CURO","CVBF","CVCY","CVII","CVLY","CWBC","CWD","CXAC","CZFS","CZNC","CZWI","DB","DCOM","DECA","DFIN",
                   "DFS","DGICA","DGICB","DHAC","DHCA","DHIL","DISA","DIST","DKDCA","DMAQ","DMYY","DNB","DPCS","DSAQ","DUET","DUNE","DWAC","DXF","EAC",
                   "EBC","EBMT","EBTC","ECBK","ECC","ECPG","EFHT","EFSC","EG","EGBN","EGGF","EHTH","EIG","EMCG","EMLD","ENCP","ENER","ENVA","EQBK","EQH",
                   "EQS","ERIE","ESAC","ESGR","ESHA","ESLA","ESNT","ESQ","ESSA","EVBN","EVE","EVGR","EVR","EVT","EWBC","EZPW","FAF","FANH","FATP","FBIZ",
                   "FBK","FBMS","FBNC","FBP","FBYD","FCAP","FCBC","FCCO","FCF","FCFS","FCNCA","FCNCO","FDBC","FDS","FDUS","FEXD","FFBC","FFIC","FFIN",
                   "FFNW","FFWM","FG","FGBI","FGF","FHB","FHI","FHLT","FHN","FIAC","FIBK","FICV","FIHL","FINV","FINW","FISI","FITB","FLFV","FLIC","FLME",
                   "FMAO","FMBH","FMNB","FNB","FNCB","FNF","FNLC","FNVT","FNWB","FNWD","FOA","FORL","FRAF","FRBA","FRBN","FRHC","FRLA","FRME","FRST",
                   "FRXB","FSBC","FSBW","FSEA","FSFG","FSK","FSNB","FSRX","FTII","FULT","FUNC","FUSB","FUTU","FVCB","FXNC","GABC","GAIN","GAMC","GAQ",
                   "GATE","GBBK","GBCI","GBDC","GBLI","GBNY","GCBC","GCMG","GDNR","GDOT","GDST","GECC","GFR","GGAL","GHI","GHIX","GHL","GHLD","GIA","GL",
                   "GLAD","GLBZ","GLLI","GLRE","GLST","GMFI","GNTY","GNW","GOCO","GODN","GPAC","GREE","GRNT","GROW","GS","GSBC","GSBD","GSD","GSHD","GTAC",
                   "HAFC","HAIA","HALL","HBAN","HBCP","HBNC","HBT","HCI","HCMA","HCVI","HDB","HFBL","HFRO","HFWA","HGBL","HGTY","HHGC","HHLA","HIFS","HIG",
                   "HIPO","HIVE","HLI","HLNE","HMN","HMNF","HMST","HNNA","HNRA","HNVR","HOMB","HONE","HOPE","HPLT","HRTG","HRZN","HSBC","HSPO","HTBI",
                   "HTBK","HTGC","HTH","HTLF","HUDA","HUIZ","HUT","HWBK","HWC","HWEL","HYAC","HYW","IBCP","IBKR","IBN","IBOC","IBTX","ICCH","ICE","ICMB",
                   "IFIN","IFS","IGIC","IGTA","IMAQ","INAQ","INBK","INDB","ING","INTE","INTR","IOAC","IOR","IPVF","IPXX","IRAA","IREN","IROQ","IRRX",
                   "ISRL","ISTR","ITAQ","ITCL","ITIC","ITUB","IVCA","IVCB","IVCP","IVZ","IX","IXAQ","JAQC","JEF","JGGC","JHG","JMSB","JPM","JRVR","JT",
                   "JUN","JWSM","JXN","KACL","KB","KCGI","KEY","KFFB","KINS","KKR","KMPR","KNSL","KNSW","KRNL","KRNY","KVAC","KVSA","KYCH","L","LARK",
                   "LATG","LAZ","LBAI","LBBB","LBC","LC","LCA","LCAA","LCNB","LCW","LDI","LGHL","LGST","LGVC","LHC","LIBY","LIVB","LKFN","LMFA","LMND",
                   "LNC","LNKB","LOB","LOCC","LPLA","LPRO","LRFC","LSBK","LU","LX","LYG","MA","MACA","MAIN","MAQC","MARA","MARX","MBAC","MBCN","MBI",
                   "MBIN","MBTC","MBWM","MC","MCAA","MCAC","MCAF","MCAG","MCB","MCBC","MCBS","MCO","MCVT","MCY","MDBH","MDWT","MEGL","MET","MFC","MFG",
                   "MFIC","MFIN","MGLD","MGYR","MHLD","MIGI","MITA","MKL","MKTX","MMC","MNSB","MNTN","MOBV","MOFG","MORN","MPB","MRBK","MRCC","MS","MSBI",
                   "MSCI","MSSA","MTAL","MTB","MTG","MTRY","MUFG","MVBF","MYFW","NAVI","NBHC","NBN","NBST","NBTB","NCAC","NCPL","NDAQ","NECB","NETC",
                   "NETD","NEWT","NFBK","NFNT","NFYS","NIC","NICK","NISN","NKSH","NMFC","NMIH","NMR","NNAG","NNI","NOAH","NODK","NOVV","NPAB","NRAC",
                   "NRDS","NRIM","NSTB","NSTS","NTB","NTRS","NU","NUBI","NVAC","NVNI","NWBI","NWFL","NWG","NWLI","NYCB","OAKU","OBDC","OBK","OBT",
                   "OCAX","OCCI","OCFC","OCN","OCSL","OFG","OFS","OHAA","OLIT","OMF","ONB","ONYX","OPA","OPBK","OPHC","OPOF","OPRT","OPY","ORI","ORRF",
                   "OSBC","OSI","OTEC","OVBC","OVLY","OWL","OXBR","OXLC","OXSQ","OXUS","OZK","PACI","PACW","PAX","PB","PBAX","PBBK","PBFS","PBHC","PCB",
                   "PCCT","PDLB","PEBK","PEBO","PEGR","PEPL","PFBC","PFC","PFG","PFIS","PFLT","PFS","PFSI","PFTA","PFX","PGC","PGR","PGSS","PHYT","PIPR",
                   "PJT","PKBK","PLAO","PLBC","PLMI","PLMR","PLTN","PMTS","PNBK","PNC","PNFP","PNNT","PORT","PPBI","PPHP","PPYA","PRA","PRAA","PRI","PRK",
                   "PRLH","PROV","PRPC","PRSR","PRU","PSEC","PT","PTHR","PTMN","PTRS","PTWO","PUCK","PUK","PUYI","PVBC","PWM","PWOD","PWP","PWUP","PX",
                   "PYPL","QCRH","QD","QDRO","QETA","QFIN","QFTA","QOMO","RACY","RAND","RBB","RBCAA","RBKB","RCAC","RCFA","RDN","RDZN","RELI","RENE","RF",
                   "RFAC","RGA","RILY","RJF","RKT","RLI","RM","RMBI","RMGC","RNR","RNST","ROCL","ROOT","ROSE","ROSS","RRAC","RRBI","RVSB","RWAY","RWOD",
                   "RY","RYAN","SAFT","SAGA","SAI","SAMA","SAMG","SAN","SAR","SASR","SBCF","SBFG","SBSI","SBT","SBXC","SCHW","SCM","SCRM","SCU","SDIG",
                   "SEDA","SEIC","SEPA","SEZL","SF","SFBC","SFBS","SFE","SFNC","SFST","SGII","SHAP","SHBI","SHFS","SHG","SHUA","SIEB","SIGI","SII","SKGR",
                   "SKWD","SLAC","SLAM","SLF","SLM","SLQT","SLRC","SMAP","SMBC","SMBK","SMFG","SMMF","SNEX","SNFCA","SNTG","SNV","SOFI","SPFI","SPGI",
                   "SPKL","SPNT","SRBK","SRCE","SRL","SSB","SSBI","SSBK","SSSS","STBA","STC","STEL","STEP","STT","SUAC","SUPV","SVII","SVVC","SWAG","SWIN",
                   "SWKH","SWSS","SYBT","SYF","SYM","SZZL","TBBK","TBCP","TBMC","TBNK","TCBC","TCBI","TCBK","TCBS","TCBX","TCJH","TCOA","TCPC","TD","TENK",
                   "TETE","TFC","TFIN","TFSL","TGAA","TGVC","THCP","THFF","THG","TIGR","TIPT","TIRX","TLGY","TMP","TMTC","TOP","TOWN","TPG","TPVG","TRCA",
                   "TREE","TRIN","TRIS","TRMK","TRON","TROW","TRST","TRTL","TRUP","TRV","TSBK","TSLX","TURN","TW","TWLV","TWOA","TYG","UBCP","UBFO","UBS",
                   "UBSI","UCBI","UFCS","UMBF","UNB","UNM","UNTY","UPST","USB","USCB","USCT","UTF","UTG","UVE","UVSP","UWMC","V","VABK","VALU","VAQC",
                   "VBFC","VBNK","VBTX","VCTR","VCXA","VCXB","VEL","VERY","VHAQ","VII","VINP","VIRT","VLY","VMCA","VOYA","VRTS","VSAC","WABC","WAFD","WAL",
                   "WASH","WAVS","WBS","WD","WDH","WEL","WF","WFC","WHF","WHG","WINV","WMPN","WNEB","WNNR","WRAC","WRB","WRLD","WSBC","WSBF","WSFS","WT",
                   "WTBA","WTFC","WTM","WTMA","WTW","WU","WULF","WWAC","XFIN","XP","XPDB","XYF","YOTA","YRD","ZION","ZLS"]

# NYSE - Sector - Healthcare
NYSE_HEALTHCARE = ["A","AADI","ABBV","ABCL","ABCM","ABEO","ABIO","ABOS","ABSI","ABT","ABUS","ABVC","ACAD","ACB","ACCD","ACER","ACET","ACHC","ACHL","ACHV",
                   "ACIU","ACLX","ACON","ACOR","ACRS","ACRV","ACRX","ACST","ACXP","ADAG","ADAP","ADCT","ADIL","ADMA","ADPT","ADTX","ADUS","ADVM","ADXN",
                   "AEMD","AEON","AEZS","AFIB","AFMD","AGE","AGEN","AGIO","AGL","AGLE","AGRX","AGTI","AHCO","AIH","AIM","AIMD","AIRS","AKAN","AKBA","AKLI",
                   "AKRO","AKTX","AKU","AKYA","ALC","ALDX","ALEC","ALGN","ALGS","ALHC","ALIM","ALKS","ALLK","ALLO","ALLR","ALNY","ALPN","ALRN","ALT","ALUR",
                   "ALVO","ALVR","ALXO","ALZN","AMAM","AMED","AMEH","AMGN","AMLX","AMN","AMPE","AMPH","AMRN","AMRX","AMS","AMTI","AMWL","ANAB","ANEB","ANGO",
                   "ANIK","ANIP","ANIX","ANL","ANNX","ANTX","ANVS","AORT","APDN","APGE","APLM","APLS","APLT","APM","APRE","APTO","APVO","APYX","AQST","ARAV",
                   "ARAY","ARCT","ARDX","ARGX","ARMP","ARQT","ARTL","ARVN","ARWR","ASLN","ASMB","ASND","ASRT","ASXC","ATAI","ATEC","ATHA","ATHE","ATHX",
                   "ATIP","ATNF","ATNM","ATOS","ATR","ATRA","ATRC","ATRI","ATXI","ATXS","AUGX","AUPH","AURA","AUTL","AVAH","AVDL","AVGR","AVIR","AVNS",
                   "AVRO","AVTE","AVTX","AVXL","AWH","AXDX","AXGN","AXLA","AXNX","AXSM","AYTU","AZN","AZTA","AZTR","BACK","BAX","BBIO","BBLG","BCAB","BCDA",
                   "BCEL","BCLI","BCRX","BCTX","BCYC","BDRX","BDSX","BDTX","BDX","BEAM","BEAT","BFLY","BFRG","BFRI","BGNE","BGXX","BHC","BHG","BHVN","BIAF",
                   "BIIB","BIMI","BIO","BIOC","BIOL","BIOR","BIVI","BJDX","BKD","BLCO","BLFS","BLPH","BLRX","BLTE","BLUE","BMEA","BMRA","BMRN","BMY","BNGO",
                   "BNOX","BNR","BNTC","BNTX","BOLT","BPMC","BPTH","BPTS","BRKR","BRTX","BSGM","BSX","BTAI","BTCY","BTMD","BTTX","BVS","BWAY","BWV","BXRX",
                   "BYSI","CABA","CADL","CAH","CALT","CANF","CANO","CAPR","CARA","CARM","CASI","CATX","CBAY","CBIO","CBUS","CCCC","CCEL","CCLD","CCM","CCRN",
                   "CDIO","CDMO","CDNA","CDT","CDTX","CDXC","CDXS","CELC","CELU","CELZ","CERE","CERS","CERT","CFRX","CGC","CGEM","CGEN","CGTX","CHE","CHEK",
                   "CHRS","CI","CING","CJJD","CKPT","CLDI","CLDX","CLGN","CLLS","CLNN","CLOV","CLPT","CLRB","CLSD","CLVR","CMAX","CMMB","CMND","CMPS","CMPX",
                   "CMRA","CMRX","CNC","CNMD","CNSP","CNTA","CNTB","CNTG","CNTX","COCP","CODX","COEP","COGT","COLL","COO","CORT","COSM","COYA","CPHI","CPIX",
                   "CPRX","CPSI","CRBP","CRBU","CRDF","CRDL","CRIS","CRL","CRMD","CRNX","CRON","CRSP","CRVO","CRVS","CSBR","CSTL","CTCX","CTKB","CTLT","CTMX",
                   "CTSO","CTXR","CUE","CUTR","CVAC","CVKD","CVM","CVRX","CVS","CWBR","CYBN","CYCC","CYCN","CYH","CYT","CYTH","CYTK","CYTO","DARE","DAWN",
                   "DBVT","DCGO","DCPH","DCTH","DERM","DGX","DH","DHR","DMAC","DMK","DMTK","DNA","DNLI","DNTH","DOCS","DOMH","DRIO","DRMA","DRRX","DRTS",
                   "DRUG","DSGN","DTIL","DVA","DVAX","DXCM","DXR","DYAI","DYN","DYNT","EAR","EBS","ECOR","EDAP","EDIT","EDSA","EFTR","EGRX","EHAB","EHC",
                   "EIGR","EKSO","ELAN","ELDN","ELEV","ELMD","ELOX","ELTX","ELUT","ELV","ELVN","ELYM","EMBC","ENLV","ENSC","ENSG","ENTA","ENTX","ENVB",
                   "ENZ","EOLS","EPIX","EQ","EQRX","ERAS","ERNA","ESPR","ESTA","ETAO","ETNB","ETON","EUDA","EVAX","EVGN","EVH","EVLO","EVO","EVOK","EW",
                   "EWTX","EXAI","EXAS","EXEL","EYEN","EYPT","FATE","FBIO","FBRX","FDMT","FEMY","FENC","FGEN","FHTX","FIXX","FLGC","FLGT","FMS","FNA",
                   "FNCH","FOLD","FONR","FORA","FOXO","FREQ","FRES","FRLN","FRTX","FTRE","FULC","FUSN","FWBI","GALT","GANX","GBIO","GBNH","GCTK","GDRX",
                   "GDTC","GEG","GEHC","GENE","GERN","GH","GHRS","GHSI","GILD","GKOS","GLMD","GLPG","GLSI","GLTO","GLUE","GLYC","GMAB","GMDA","GMED","GNFT",
                   "GNLX","GNPX","GNTA","GOSS","GOVX","GPCR","GRCL","GRFS","GRI","GRPH","GRTS","GRTX","GSK","GTBP","GTH","GTHX","HAE","HALO","HARP","HBIO",
                   "HCA","HCAT","HCM","HCSG","HCTI","HCWB","HEPA","HITI","HLN","HLTH","HLVX","HOLX","HOOK","HOTH","HOWL","HPCO","HQY","HRMY","HROW","HRTX",
                   "HSCS","HSDT","HSIC","HSTM","HUGE","HUM","HUMA","HYPR","HZNP","IART","IBIO","IBRX","ICAD","ICCC","ICCM","ICCT","ICLR","ICPT","ICU","ICUI",
                   "ICVX","IDXX","IDYA","IFRX","IGMS","IINN","IKNA","IKT","ILMN","IMAB","IMCC","IMCR","IMGN","IMMP","IMMX","IMNM","IMNN","IMPL","IMRN",
                   "IMRX","IMTX","IMUX","IMVT","INAB","INBS","INBX","INCR","INCY","INDP","INDV","INFU","INGN","INKT","INM","INMB","INMD","INNV","INO","INSM",
                   "INSP","INTS","INVA","INVO","INZY","IOBT","IONM","IONS","IOVA","IPA","IPHA","IPSC","IQV","IRIX","IRMD","IRON","IRTC","IRWD","ISPC","ISRG",
                   "ITCI","ITGR","ITOS","ITRM","IVA","IVVD","IXHL","JAGX","JANX","JAZZ","JNJ","JSPR","JYNT","KA","KALA","KALV","KERN","KIDS","KMDA","KNSA",
                   "KNTE","KOD","KPRX","KPTI","KRMD","KRON","KROS","KRTX","KRYS","KTRA","KTTA","KURA","KYMR","KZIA","KZR","LAB","LABP","LBPH","LCTX","LEGN",
                   "LEXX","LFCR","LFLY","LFMD","LFST","LGND","LGVN","LH","LIAN","LIFE","LIFW","LIPO","LIVN","LIXT","LLY","LMAT","LMDX","LNSR","LNTH","LPCN",
                   "LPTX","LQDA","LRMR","LSDI","LSTA","LTRN","LUCD","LUCY","LUMO","LUNG","LVTX","LXRX","LYEL","LYRA","MACK","MAIA","MASI","MASS","MBIO",
                   "MBOT","MBRX","MCK","MCRB","MD","MDAI","MDGL","MDGS","MDNA","MDRX","MDT","MDVL","MDWD","MDXG","MDXH","ME","MEDP","MEDS","MEIP","MESO",
                   "MGNX","MGRM","MGRX","MGTX","MHUA","MIRA","MIRM","MIRO","MIST","MLEC","MLSS","MLTX","MLYS","MMSI","MNKD","MNMD","MNOV","MNPR","MODD",
                   "MODV","MOH","MOLN","MOR","MORF","MOTS","MOVE","MPLN","MRAI","MREO","MRK","MRKR","MRNA","MRNS","MRSN","MRTX","MRUS","MRVI","MTD","MTEM",
                   "MTNB","MXCT","MYGN","MYMD","MYNZ","MYO","NAMS","NAOV","NARI","NAUT","NBIX","NBSE","NBTX","NBY","NCNA","NDRA","NEO","NEOG","NEPH","NEPT",
                   "NERV","NEXI","NGM","NHC","NHWK","NKGN","NKTR","NKTX","NLSP","NLTX","NMRA","NMRD","NMTC","NNOX","NNVC","NOTV","NPCE","NRBO","NRC","NRIX",
                   "NRSN","NRXP","NRXS","NSPR","NSTG","NTLA","NTRA","NTRB","NURO","NUTX","NUVB","NUVL","NUWE","NVAX","NVCR","NVCT","NVIV","NVNO","NVO",
                   "NVRO","NVS","NVST","NVTA","NXGL","NXGN","NXL","NXTC","NYXH","OABI","OBIO","OCEA","OCGN","OCS","OCUL","OCUP","OCX","OFIX","OGEN","OGI",
                   "OGN","OKYO","OLK","OLMA","OM","OMCL","OMER","OMGA","OMI","OMIC","ONCT","ONCY","ONTX","ONVO","OPCH","OPGN","OPK","OPRX","OPT","OPTN",
                   "ORGO","ORGS","ORIC","ORMP","ORTX","OSA","OSCR","OSUR","OTLK","OTRK","OVID","OWLT","PACB","PAHC","PALI","PASG","PAVM","PBH","PBLA",
                   "PBYI","PCRX","PCSA","PCVX","PDCO","PDEX","PDSB","PEN","PEPG","PETQ","PETS","PETV","PFE","PGEN","PGNY","PHAR","PHAT","PHG","PHGE","PHIO",
                   "PHR","PHVS","PHXM","PIII","PINC","PIRS","PLRX","PLSE","PLUR","PLX","PMCB","PMD","PMN","PMVP","PNT","PNTG","POAI","PODD","PPBT","PRAX",
                   "PRCT","PRE","PRFX","PRGO","PRLD","PRME","PROC","PROF","PROK","PRPH","PRPO","PRQR","PRTA","PRTC","PRTG","PRVA","PSNL","PSTV","PSTX",
                   "PTCT","PTGX","PTIX","PTN","PTPI","PULM","PXMD","PYPD","PYXS","QDEL","QGEN","QIPT","QLGN","QLI","QNCX","QNRX","QSI","QTRX","QURE","RAD",
                   "RAIN","RANI","RAPT","RARE","RBOT","RCEL","RCKT","RCM","RCUS","RDHL","RDNT","RDUS","RDY","REGN","RENB","REPL","REVB","RGC","RGEN","RGLS",
                   "RGNX","RHE","RIGL","RLAY","RLMD","RLYB","RMD","RMTI","RNA","RNAZ","RNLX","RNXT","ROIV","RPHM","RPID","RPRX","RPTX","RSLS","RVLP","RVMD",
                   "RVNC","RVP","RVPH","RVTY","RWLK","RXRX","RXST","RYTM","RYZB","RZLT","SABS","SAGE","SANA","SAVA","SBFM","SCLX","SCNI","SCPH","SCTL",
                   "SCYX","SDGR","SEEL","SEER","SELB","SEM","SENS","SERA","SGEN","SGHT","SGMO","SGMT","SGRY","SHC","SHCR","SHLT","SHOT","SHPH","SIBN",
                   "SIEN","SIGA","SILK","SILO","SINT","SISI","SLDB","SLGC","SLGL","SLN","SLNO","SLP","SLRN","SLRX","SLS","SMLR","SMMT","SMTI","SNCE","SNDA",
                   "SNDL","SNDX","SNGX","SNN","SNOA","SNPX","SNSE","SNTI","SNY","SONN","SONX","SOPH","SPOK","SPRB","SPRC","SPRO","SPRY","SQL","SRDX","SRPT"
                   ,"SRRK","SRTS","SRZN","SSIC","SSKN","SSY","STAA","STE","STIM","STOK","STRM","STRO","STRR","STSS","STTK","STVN","STXS","SUPN","SVRA",
                   "SWAV","SWTX","SXTC","SXTP","SY","SYBX","SYK","SYRA","SYRS","TAK","TALK","TALS","TARA","TARO","TARS","TBIO","TBPH","TCBP","TCMD","TCON",
                   "TCRT","TCRX","TDOC","TECH","TELA","TENX","TERN","TEVA","TFFP","TFX","TGTX","THAR","THC","THMO","THRD","THRX","THTX","TIL","TIVC","TKNO",
                   "TLIS","TLRY","TLSA","TLSI","TMBR","TMCI","TMDX","TMO","TNDM","TNGX","TNON","TNXP","TNYA","TOI","TOVX","TPST","TRDA","TRHC","TRIB",
                   "TRVI","TRVN","TSBX","TSHA","TSVT","TTNP","TTOO","TVTX","TWST","TXG","TXMD","TYRA","UBX","UFPT","UHS","UNCY","UNH","UPC","UPH","URGN",
                   "USPH","UTHR","UTMD","UTRS","VACC","VALN","VANI","VAPO","VAXX","VBIV","VBLT","VCEL","VCNX","VCYT","VEEV","VERA","VERO","VERU","VERV",
                   "VIGL","VINC","VIR","VIRI","VIRX","VKTX","VMD","VNDA","VNRX","VOR","VRAX","VRCA","VRDN","VREX","VRNA","VRPX","VRTX","VSTM","VTAK",
                   "VTGN","VTRS","VTVT","VTYX","VVOS","VXRT","VYGR","VYNE","WAT","WBA","WGS","WINT","WORX","WRBY","WST","WVE","XAIR","XBIO","XBIT","XCUR",
                   "XENE","XERS","XFOR","XGN","XLO","XNCR","XOMA","XRAY","XRTX","XTLB","XTNT","YCBD","YI","YMAB","YS","ZBH","ZCMD","ZIMV","ZIVO","ZJYL",
                   "ZLAB","ZNTL","ZOM","ZTEK","ZTS","ZURA","ZVRA","ZVSA","ZYME","ZYNE","ZYXI"]

# NYSE - Sector - Industrials
NYSE_INDUSTRIALS = ["AAL","AAN","AAON","ABM","ACA","ACCO","ACHR","ACM","ACTG","ADES","ADP","ADSE","ADT","AEHL","AEIS","AENZ","AER","AGCO","AGFY","AGX",
                    "AIR","AIRI","AIRT","AIT","AL","ALG","ALGT","ALK","ALLE","ALPP","ALTG","AMBI","AME","AMPX","AMRC","AMSC","AOS","AP","APG","APOG",
                    "APT","APWC","AQMS","ARC","ARCB","ARLO","ARMK","ARTW","ASC","ASLE","ASPN","ASR","ASTC","ASTE","ASTR","ATI","ATKR","ATMU","ATRO",
                    "ATS","ATSG","ATXG","AULT","AVAV","AVY","AWI","AWX","AXON","AYI","AZ","AZEK","AZUL","AZZ","B","BA","BAER","BAH","BBCP","BBSI","BBU",
                    "BCO","BE","BECN","BEEP","BEST","BGSF","BKYI","BLD","BLDE","BLDP","BLDR","BLNK","BRC","BURU","BV","BW","BWEN","BWMN","BWXT","BXC",
                    "BYRN","BZ","CAAP","CACO","CAE","CAR","CARR","CASS","CAT","CBAT","CBZ","CDRE","CEAD","CECO","CHNR","CHRW","CIR","CISS","CIX","CLCO",
                    "CLH","CLIR","CLWT","CMCO","CMI","CMPO","CMRE","CNHI","CNI","CNM","CODA","CODI","CP","CPA","CPLP","CR","CRAI","CRESY","CRGO","CRS",
                    "CSL","CSTE","CSWI","CSX","CTAS","CTOS","CTRM","CVEO","CVLG","CVR","CVU","CVV","CW","CWST","CXT","CYD","CYRX","DAC","DAL","DCFC",
                    "DCI","DCO","DE","DFLI","DGLY","DHX","DLHC","DOOR","DOV","DPRO","DRS","DSGR","DSKE","DSX","DXPE","DY","EAF","EBF","EDRY","EFSH","EFX",
                    "EGLE","EH","EME","EML","EMR","ENG","ENOV","ENR","ENS","ENVX","EOSE","EPAC","EPOW","ERII","ERJ","ESAB","ESEA","ESGL","ESLT","ESOA",
                    "ESP","ETN","EVEX","EVI","EVLV","EVTL","EXPD","EXPO","FA","FAST","FBIN","FC","FCEL","FCN","FDX","FELE","FERG","FIP","FIX","FLR","FLS",
                    "FLUX","FORR","FPAY","FREY","FSS","FSTR","FTAI","FTEK","FWRD","GASS","GATX","GBX","GD","GE","GENC","GEO","GFAI","GFF","GFL","GGG",
                    "GHM","GIC","GIFI","GLBS","GLDD","GMS","GNK","GNRC","GOGL","GOL","GPN","GRC","GRIN","GRNQ","GSL","GTEC","GTES","GTLS","GVA","GWAV",
                    "GWH","GWW","GXO","HA","HAYN","HAYW","HCCI","HEES","HEI","HEI.A","HI","HIHO","HII","HLIO","HLMN","HNI","HOLI","HON","HQI","HRI",
                    "HRT","HSHP","HSII","HSON","HTLD","HTZ","HUBB","HUBG","HURC","HURN","HWM","HXL","HY","HYFM","IBP","ICFI","IDEX","IEP","IESC","IEX",
                    "IGC","IIIN","ILAG","IPDN","IPWR","IR","IRS","ISSC","ITT","ITW","IVAC","IVDA","J","JAN","JBHT","JBI","JBLU","JBT","JCI","JCSE","JELD",
                    "JOB","JOBY","JYD","KAI","KAMN","KBR","KE","KELYA","KELYB","KEX","KFRC","KFY","KIQ","KITT","KMT","KNOP","KNX","KODK","KRNT","KSCP",
                    "KTOS","KWE","LASE","LECO","LEV","LGMK","LHX","LICN","LICY","LII","LILM","LIQT","LLAP","LMB","LMT","LNN","LNZA","LPX","LSTR","LTBR",
                    "LUNR","LUV","LXFR","LZ","MAN","MAS","MATW","MATX","MDU","MEC","MEG","MESA","MG","MGRC","MHH","MIDD","MIR","MKUL","MLI","MMM","MMS",
                    "MNTS","MNTX","MOG.A","MOG.B","MPU","MRCY","MRTN","MSA","MSM","MTRX","MTW","MTZ","MVST","MWA","MWG","MYRG","NAT","NDSN","NEOV","NETI",
                    "NKLA","NL","NM","NMM","NNBR","NOC","NPK","NPO","NPWR","NSC","NSP","NSSC","NTIP","NVEE","NVRI","NVT","NVX","NWPX","NX","NXU","OC",
                    "ODFL","OESX","OFLX","OMAB","OMEX","OP","OPTT","OPXS","ORN","OSK","OTIS","PAC","PANL","PATI","PAYX","PBI","PCAR","PCT","PESI","PFIN",
                    "PFMT","PFSW","PGTI","PH","PIXY","PKE","PKOH","PL","PLPC","PLUG","PNR","POLA","POOL","POWL","POWW","PPIH","PPSI","PRG","PRIM","PRLB",
                    "PRZO","PSHG","PSN","PTSI","PWR","PXS","PYR","QRHC","QUAD","R","RAIL","RAYA","RBA","RBC","RCMT","RCRT","RDW","REVG","REZI","RFIL",
                    "RGP","RGR","RHI","RKLB","RLGT","ROAD","ROCK","ROK","ROP","RRX","RSG","RTO","RTX","RVSN","RXO","RYAAY","RYI","SAIA","SAVE","SB","SBLK",
                    "SCS","SCWO","SCX","SEB","SFL","SFWL","SGBX","SGLY","SGRP","SHIP","SHPW","SHYF","SIDU","SIF","SITE","SKYH","SKYW","SKYX","SLDP","SLND",
                    "SMX","SNA","SNCY","SNDR","SNT","SP","SPCB","SPCE","SPIR","SPLP","SPPL","SPR","SPXC","SRCL","SRFM","SSD","SST","STAF","STN","STRL",
                    "SVT","SWBI","SWIM","SWK","SXI","TATT","TAYD","TBI","TBLT","TDCX","TDG","TEX","TFII","TG","TGH","TGI","TH","THR","TISI","TITN","TKR",
                    "TNC","TNET","TOMZ","TOPS","TORO","TPC","TPIC","TRC","TREX","TRI","TRN","TRNS","TRU","TSP","TT","TTC","TTEK","TURB","TUSK","TWI",
                    "TWIN","TXT","UAL","UGRO","UHAL","ULBI","ULCC","ULH","UNF","UNP","UP","UPS","UPWK","URI","USDP","USEA","UUU","VATE","VCIG","VIEW",
                    "VLRS","VLTO","VMI","VRME","VRRM","VRSK","VRT","VRTV","VSEC","VSTS","VTSI","VVI","VVX","WAB","WCC","WCN","WERN","WHLM","WIRE","WLDN",
                    "WLFC","WLGS","WM","WMS","WNC","WOR","WSC","WSO","WTS","WWD","XMTR","XOS","XPO","XPON","XYL","YGMZ","ZIM","ZIP","ZTO","ZWS"]

# NYSE - Sector - Materials
NYSE_MATERIALS = ["AA","AAU","ABAT","ACNT","AEM","AG","AGI","ALB","ALTO","AMLI","AMR","APD","AREC","ARMN","ASH","ASIX","ASM","ASPI","ASTL","ATLX","AU",
                  "AUMN","AUST","AVD","AVNT","AVTR","AXTA","BAK","BCC","BCPC","BHIL","BHP","BIOX","BTG","BVN","CBT","CC","CCF","CDE","CE","CENX","CF",
                  "CGA","CGAU","CLF","CLW","CMC","CMCL","CMP","CMT","CNEY","CPAC","CRH","CRKN","CSTM","CTGO","CTVA","CX","DC","DD","DNMR","DOW","DRD",
                  "ECL","ECVT","EGO","EIC","ELBM","EMN","EMX","EQX","ERO","ESI","EVA","EXK","EXP","FCX","FEAM","FF","FMC","FNV","FRD","FSI","FSM","FUL",
                  "FURY","GATO","GAU","GEVO","GFI","GGB","GLDG","GLG","GLT","GOLD","GORO","GPRE","GRFX","GROY","GSM","GURE","HBM","HCC","HDSN","HL",
                  "HLP","HMY","HUDI","HUN","HWKN","HYMC","IAG","IAUX","ICL","IDR","IFF","IONR","IOSP","IPI","IPX","ITP","ITRG","JCTCF","JHX","KALU",
                  "KGC","KNF","KOP","KRO","KWR","LAC","LGO","LIN","LITM","LOMA","LOOP","LTHM","LVRO","LWLG","LXU","LYB","LZM","MAG","MATV","MEOH",
                  "MERC","METC","METCB","MLM","MOS","MP","MSB","MT","MTA","MTRN","MTX","MUX","NAK","NB","NEM","NEU","NEWP","NEXA","NFGC","NG","NGD",
                  "NGVT","NMG","NTIC","NTR","NUE","NWGL","ODC","ODV","OEC","OLN","OR","ORGN","ORLA","PAAS","PKX","PLG","PLL","PLM","PPG","PPTA","PRM",
                  "PZG","RETO","REX","RGLD","RIO","RKDA","RPM","RS","RYAM","SA","SAND","SBSW","SCCO","SCL","SEED","SGML","SHW","SID","SILV","SIM","SKE",
                  "SLI","SLVM","SMG","SMID","SNES","SQM","SSL","SSRM","STLD","STR","SUM","SUZ","SVFD","SVM","SXC","SXT","TBLD","TECK","TFPM","TGB",
                  "TGLS","THM","TMC","TMQ","TMST","TROX","TRX","TSE","TX","UAMY","UAN","UFPI","USAP","USAS","USAU","USGO","USLM","VALE","VGZ","VHI",
                  "VMC","VOXR","VZLA","WDFC","WFG","WLK","WLKP","WPM","WRN","WWR","X","XPL","YTEN","ZEUS","ZKIN"]

# NYSE - Sector - Real Estate
NYSE_REAL_ESTATE = ["AAIC","AAT","ABR","ACR","ACRE","ADC","AEI","AFCG","AGNC","AHH","AHT","AIRC","AIV","AJX","AKR","ALBT","ALEX","ALX","AMH","AMT","AOMR",
                    "APLE","ARE","ARI","ARL","ARR","ASPS","AVB","AXR","BDN","BEKE","BFS","BHM","BHR","BNL","BRSP","BRT","BRX","BXMT","BXP","CBL","CBRE",
                    "CCI","CDP","CHCI","CHCT","CHMI","CIGI","CIM","CIO","CLDT","CLPR","CMCT","CMTG","COLD","COR","CORR","CPT","CSGP","CSR","CTO","CTRE",
                    "CUBE","CUZ","CWK","CXW","DBRG","DEA","DEI","DHC","DLR","DOC","DOMA","DOUG","DRH","DUO","DX","EARN","EFC","EGP","ELME","ELS","EPR",
                    "EPRT","EQC","EQIX","EQR","ESBA","ESRT","ESS","EXPI","EXR","FBRT","FCPT","FLJ","FOR","FPH","FPI","FR","FRPH","FRT","FSP","FSV","FTHM",
                    "GBR","GGE","GIPR","GLPI","GMRE","GNL","GOOD","GPMT","GTY","GYRO","HASI","HCDI","HHH","HIW","HOUS","HPP","HR","HST","HT","IHT","IIPR",
                    "ILPT","INN","INVH","IRM","IRT","IVR","IVT","JBGS","JLL","JOE","KIM","KRC","KREF","KRG","KW","LADR","LAMR","LAND","LEJU","LFT","LOAN",
                    "LODE","LSEA","LTC","LXP","MAA","MAC","MAYS","MDJH","MDRR","MDV","MFA","MITT","MLP","MMI","MPW","NEN","NHI","NLY","NMRK","NNN","NREF",
                    "NSA","NTST","NXRT","NYC","NYMT","O","OHI","OLP","OMH","ONL","OPAD","OPEN","OPI","ORC","OUT","OZ","PCH","PDM","PEAK","PEB","PECO",
                    "PGRE","PGRU","PINE","PK","PLD","PLYM","PMT","PSA","PSTL","PW","RC","RDFN","REAX","REFI","REG","REXR","RFL","RHP","RITM","RLJ","RMAX",
                    "RMR","ROIC","RPT","RWT","RYN","SACH","SAFE","SBAC","SBRA","SELF","SEVN","SFR","SHO","SITC","SKT","SLG","SOHO","SPG","SQFT","SRC",
                    "SRG","STAG","STHO","STRS","STRW","STWD","SUI","SVC","TCI","TCN","TPHS","TRNO","TRTX","TWO","UDR","UE","UHT","UK","UMH","UNIT","VICI",
                    "VINO","VNO","VRE","VTMX","VTR","WE","WELL","WHLR","WMC","WPC","WSR","WY","XHR","XIN"]

# NYSE - Sector - Technology
NYSE_TECH = ["AAOI","AAPL","ACIW","ACLS","ACN","ADBE","ADEA","ADI","ADSK","ADTN","AEHR","AEY","AEYE","AFRM","AGIL","AGMH","AGYS","AHI","AI","AIP","AIRG",
             "AIXI","AKAM","AKTS","ALAR","ALGM","ALIT","ALKT","ALLT","ALNT","ALOT","ALRM","ALTR","ALYA","AMAT","AMBA","AMD","AMKR","AMPG","AMPL","AMST",
             "AMSWA","ANET","ANSS","ANY","AOSL","APCX","APH","API","APP","APPF","APPN","APPS","ARBB","ARBE","ARM","ARQQ","ARRY","ARW","ASAN","ASGN",
             "ASML","ASNS","ASTI","ASUR","ASX","ASYS","ATEN","ATOM","AUDC","AUID","AUR","AUUD","AVDX","AVGO","AVNW","AVPT","AVT","AWIN","AWRE","AXTI",
             "AYX","AZPN","BAND","BASE","BB","BBAI","BCAN","BCOV","BDC","BEEM","BELFA","BELFB","BHE","BIGC","BILL","BKKT","BKSY","BKTI","BL","BLBX",
             "BLIN","BLKB","BLND","BLZE","BMBL","BMI","BMR","BMTX","BOSC","BOX","BOXL","BR","BRQS","BRZE","BSQR","BSY","BTCM","BTDR","CACI","CALX",
             "CAMP","CAMT","CAN","CART","CASA","CCCS","CCRD","CCSI","CD","CDAY","CDNS","CDW","CETX","CEVA","CFLT","CGNT","CGNX","CHKP","CIEN","CINT",
             "CISO","CLBT","CLFD","CLMB","CLPS","CLRO","CLS","CLSK","CLVT","CMBM","CMTL","CNDT","CNXC","CNXN","COHR","COHU","COIN","COMM","COMP","CPSH",
             "CPTN","CRCT","CRDO","CREX","CRGE","CRM","CRNC","CRNT","CRSR","CRUS","CRWD","CSCO","CSGS","CSIQ","CSPI","CTG","CTLP","CTM","CTS","CTSH",
             "CUEN","CVLT","CWAN","CXAI","CXM","CYBR","CYN","DAIO","DAKT","DATS","DAVA","DAVE","DBD","DBX","DCBO","DDD","DDOG","DELL","DGHI","DGII","DIOD",
             "DJCO","DLB","DLO","DM","DMRC","DOCN","DOCU","DOMO","DOX","DPSI","DQ","DSGX","DSP","DSWL","DT","DTSS","DTST","DUOL","DUOT","DV","DXC",
             "DZSI","EB","EBIX","EBON","EEFT","EGAN","EGHT","EGIO","ELSE","ELTK","ELWS","EMAN","EMKR","ENFN","ENPH","ENTG","ENV","EPAM","ERIC","ESE",
             "ESMT","ESTC","ETWO","EVBG","EVCM","EVTC","EXFY","EXLS","EXTR","EZFL","FARO","FATH","FCUV","FEIM","FFIV","FI","FICO","FIS","FIVN","FKWL",
             "FLEX","FLT","FLYW","FN","FORM","FORTY","FOUR","FRGE","FRGT","FROG","FRSH","FSLR","FSLY","FTCI","FTFT","FTNT","FTV","G","GB","GBTG","GCT",
             "GDDY","GDS","GDYN","GEN","GETR","GFS","GIB","GILT","GLOB","GLW","GNSS","GPRO","GRAB","GRMN","GRND","GRRR","GSIT","GTLB","GVP","GWRE","HCKT",
             "HCP","HEAR","HIMX","HKD","HKIT","HLIT","HOLO","HOOD","HPE","HPQ","HTCR","HUBC","HUBS","IBEX","IBM","ICG","ICHR","IDAI","IDN","IE","IFBD",
             "III","IIIV","IMMR","IMOS","IMTE","IMXI","INDI","INFA","INFN","INFY","INLX","INOD","INPX","INSG","INST","INTA","INTC","INTT","INTU","INTZ",
             "INVE","IONQ","IOT","IPGP","ISDR","ISUN","IT","ITI","ITRI","ITRN","IZM","JAMF","JBL","JFU","JG","JKHY","JKS","JNPR","JNVR","JTAI","KARO",
             "KBNT","KC","KD","KEYS","KLAC","KLIC","KLTR","KN","KNW","KOPN","KOSS","KPLT","KTCC","KULR","KVHI","KVYO","LAES","LASR","LAW","LDOS","LEDS",
             "LFUS","LGL","LINK","LITE","LOGI","LPL","LPSN","LPTH","LRCX","LSAK","LSCC","LSPD","LTRX","LUNA","LVOX","LYFT","LYT","LYTS","MANH","MAPS",
             "MARK","MAXN","MCHP","MDB","MEI","MGIC","MICS","MIND","MINM","MITK","MITQ","MIXT","MKFG","MKSI","MKTW","ML","MLAB","MLGO","MLNK","MMAT","MNDO",
             "MNDY","MOB","MODN","MOGO","MPTI","MPWR","MQ","MRAM","MRDB","MRIN","MRT","MRVL","MSFT","MSI","MSN","MSTR","MTBL","MTC","MTEK","MTLS","MTSI",
             "MTTR","MU","MVIS","MVLA","MX","MXL","MYNA","MYSZ","NABL","NATI","NCNO","NCR","NEON","NET","NEWR","NICE","NIR","NNDM","NOGN","NOK","NOTE",
             "NOVA","NOVT","NOW","NRDY","NSIT","NSYS","NTAP","NTCT","NTGR","NTNX","NTWK","NVDA","NVEC","NVEI","NVMI","NVTS","NXPI","NXPL","NXT","NXTP",
             "NYAX","OBLG","OCC","OCFT","ODD","OKTA","OLB","OLED","OLO","OMQS","ON","ONDS","ONTF","ONTO","OPFI","ORCL","OSIS","OSPN","OSS","OST","OTEX",
             "OTMO","OUST","PAGS","PALT","PANW","PAR","PATH","PAY","PAYC","PAYO","PAYS","PBTS","PCOR","PCTI","PCTY","PCYG","PD","PDFS","PEGA","PEGY",
             "PERF","PET","PGY","PHUN","PI","PLAB","PLTR","PLUS","PLXS","POET","POWI","PRCH","PRFT","PRGS","PRO","PRSO","PRST","PRTH","PSFE","PSQH",
             "PSTG","PTC","PUBM","PWFL","PWSC","PXDT","PXLW","PYCR","QBTS","QCOM","QH","QLYS","QMCO","QRVO","QTWO","QUBT","QUIK","RAMP","RBT","RCAT",
             "RDVT","RDWR","REFR","REKR","RELL","RELY","RGTI","RIOT","RMBS","RMNI","RNG","ROG","RPAY","RPD","RSKD","RSSS","RTC","RUM","RUN","RVYL","RXT",
             "S","SAIC","SANG","SANM","SAP","SASI","SATL","SATS","SATX","SCKT","SCSC","SCWX","SEDG","SEMR","SGE","SGH","SGMA","SHLS","SHOP","SILC","SIMO",
             "SITM","SKYT","SLAB","SLNH","SMAR","SMCI","SMRT","SMSI","SMTC","SNCR","SNOW","SNPO","SNPS","SNX","SOBR","SOFO","SOL","SONM","SONO","SONY",
             "SOPA","SOS","SOTK","SOUN","SPI","SPLK","SPNS","SPRU","SPSC","SPT","SPWR","SQ","SQNS","SQSP","SRAD","SRT","SSNC","SSNT","SSTI","SSYS","ST",
             "STEM","STER","STIX","STM","STNE","STRC","STX","SUNW","SURG","SVRE","SWI","SWKS","SWVL","SYNA","SYT","SYTA","TACT","TAIT","TAOP","TASK","TCX",
             "TDC","TDY","TEAM","TEF","TEL","TENB","TER","TGAN","TGL","TIO","TIXT","TLS","TMPO","TOST","TRMB","TROO","TRT","TSAT","TSEM","TSM","TSRI",
             "TTD","TTEC","TTMI","TUYA","TWKS","TXN","TYGO","TYL","U","UAVS","UBER","UCTT","UEIC","UI","UIS","UMC","UPBD","UPLD","USIO","UTSI","VCSA",
             "VECO","VERB","VERI","VERX","VHC","VIAO","VIAV","VICR","VISL","VJET","VLD","VLN","VMEO","VMW","VNET","VNT","VOXX","VPG","VRAR","VRNS","VRNT",
             "VRSN","VS","VSAT","VSH","VTEX","VUZI","VVPR","VZIO","WALD","WATT","WAVD","WBX","WDAY","WDC","WEAV","WETG","WEX","WFCF","WISA","WIT","WIX",
             "WK","WKEY","WKME","WLDS","WNS","WOLF","WRAP","WRNT","WTO","WYY","XELA","XPER","XRX","YALA","YEXT","YMM","YOU","ZBRA","ZENV","ZEPP","ZETA",
             "ZFOX","ZI","ZM","ZS","ZUO"]

# NYSE - Sector - Utilities
NYSE_UTIL = ["ADN","AEE","AEP","AES","AGR","ALE","AMPS","AQN","ARIS","ARTNA","ATO","AVA","AWK","AWR","AY","BEP","BEPC","BIP","BIPC","BKH","BNRG","CDZI",
             "CEG","CEPU","CIG","CMS","CNP","CPK","CREG","CWCO","CWEN","CWEN.A","CWT","D","DTE","DUK","EBR","ED","EDN","EE","EIX","ELIQ","ELLO","ELP",
             "ENIC","ENLT","ES","ETR","EVRG","EXC","FE","FLNC","FTS","GNE","GWRS","HE","HLGN","HTOO","IDA","KEN","KEP","LNT","MGEE","MNTK","MSEX","NEE",
             "NEP","NFE","NGG","NI","NJR","NRG","NRGV","NWE","NWN","OGE","OGS","OPAL","ORA","OTTR","PAM","PCG","PCYO","PEG","PNM","PNW","POR","PPL",
             "RGCO","RNW","SBS","SJW","SMR","SO","SPH","SR","SRE","SWX","TAC","UGI","UTL","VGAS","VIA","VST","WAVE","WEC","WTRG","XEL","YORW"]

# NYSE - Sector - Real Estate Management & Development
NYSE_REAL_ESTATE_MNGMT_AND_DEV = ["LRE"]
